---
title: "Lab 1 Assignment"
author: "ANLY511"
output: rmdformats::robobook
---

One of the primary advantages of simulators is that they are able to provide users with practical feedback
when designing real world systems. This allows the designer to determine the correctness and efficiency of a
design before the system is actually constructed.
That means we do simulations to imitate real situations and fit models to check the robustness of our models
and then fit those models on real data. This is a famous method on big research areas.

# Problem 1 - Guided Activity

Take the 6-sided fair dice (or simulated [dice]<https://www.piliapp.com/random/dice/?num=1>) and roll until you reach your first three successes (_*rolling a 1*_).

Do you think the _success probability is p = 1/6 or better?_
Can a simulation give an answer? lets try.

a) Count how many trials it takes to get your first, second, and third success (_*rolling a 1*_).

b) Create two functions taking in a success probability: 'myroll' to simulate a single dice roll and 'myattempts' to find the number of failures until the first success (Hint: We have already done this in the Lab )

c) Simulate the number of rolls needed to get to three successes, use the success probability p = 1/6. (use the "myattempts" function). Assign this number to be x. (Hint: Run many simulations (say 10,000) with this success probability to find the number of failures until first three successes.)

d) Find the fraction of simulations where three successes were reached after the number of trials it took you to get three successes - with success probability 1/6. (Use the "x" variable from part 2). In other words, what percentage of the simulations did worse than the number of trials it took you to get three successes? (Hint: So now we want to find the probability of getting 3 successes after 9 tosses, that means probability of total of 6 or more tosses until I get my 3 successes)

# Problem 2 - Theoretical Questions for Discussion

In your groups take notes and discuss on the following:

a) What does it mean to set seed? How could it be useful to the study of probability and statistics?

b) How might you run a similar simulation in python? are there any functions comparable to the ones used in problem #1 and #2?

c) Reflect on your experiences during the boot camp this summer. What might be some advantages/disadvantages of R over Python?

# Problem 3

Problem 1.5 in ch. 1 of Dalgaard. On p. 27, replicate was used to simulate the distribution of the mean of 20 random numbers from the exponential distribution by repeating the operation 10 times. That code is

```{r}
replicate(10,mean(rexp(20)))
```

How would you do the same thing with `sapply`?