---
title: "ANLY511 Homework 1"
date: "8/29/2022"
output:
 output: rmdformats::robobook
---

## Problem 1 (25 points)

a) Create a standard 52 card deck, refer to the card deck created in Bootcamp Assignment 6-problem 1 (5 points)

b) What is the probability of getting two diamonds with replacement? (5 points)

c) What is the probability of getting two diamonds without replacement? (5 points)

d) Assuming a 5 card poker hand what is the probability of having four of a kind? (Hint. The probability of a 4 of a kind is equal to total number of ways to get a four of a kind divided by the total number of ways to choose 5 cards from a 52 card deck) (10 points)

## Problem 2 (20 Points)
Using the poker dataset you just created above

a) Run four simulations that pull 10, 100, 1000, and 10000 cards respectively with replacement. Use the `table` function to find the distribution of suit counts. (5 Points)

b) What do you notice about the distribution of counts as more simulations are run? (5 Points)

c) Run a simulation for Problem #1 part D to answer the question. Compare the results (hint. they should be close) (10 points)

## Problem  3 (15 points)

Consider the baby names data for 2014. Write a function that
computes the conditional probability $P(gender = F | name = XXX)$ for a given
character string XXX. Next, use the function to compute conditional probabilities for the
10 most common female baby names of that year (In other words what is probability the child is a female given the name is XXX?). For which female baby name of
the top 10 is this conditional probability maximal? What does this mean?

## Problem 4 (15 points)

Many adults find videos online and then re-post the videos on social media sights. The Pew Internet and American Life Project has found this behavior continues to increase through various polls. The results of such polling is summarized in the table below. A count for `UserCreated` means an individual from that age range prefers watching `UserCreated` videos and a count for `TV` means an individual from that age range prefers watching `TV` videos.

```{r echo = FALSE}
ViewerAge <- c("18-34","35-54","55+","ColumnTotal")
UserCreated <- c(30,10,3,43)
TV <- c(38,10,9,57)
RowTotal <- c(68,20,12,100)
as.data.frame(cbind(ViewerAge,UserCreated,TV,RowTotal))
```
Answer the following questions referring to the table above

a) Probability that a viewer is aged 18-34 (3 points)

b) Probability that a viewer prefers watching `TV` videos (4 points)

c) Percentage of viewers who are 18-34 and prefer watching `UserCreated` videos (4 points)

d) Percentage of viewers who are 35-54 or prefer watching `UserCreated` videos (4 points)

## Problem 5 (15 points)

Suppose $X$ and $Y$ are independent random variables that both have uniform $U(0,1)$ distributions. Consider the events

$$
A = \{X < \frac{1}{2}\}, \quad B = \{Y < \cos \pi X\} \, . 
$$

Then $P(A) = \frac{1}{2}$. Use __R__ and simulations to estimate $P(B), \, P(A|B), P(B|A)$. 

a) `R` will automatically generate independent random variables in a simulation. Use `runif(n)` to simulate 100,000 Uniform(0,1) distributed random values. Make a data frame for $X$ and $Y$ uniform random variables, compute two additional columns for the events $A$ and $B$ as given in the problem, and estimate the relevant probabilities by sub-setting. (4 points)

b) Find $P(B)$ (3 points)

c) Find $P(A|B)$ (4 points)

d) Find $P(B|A)$ (4 points)

## Problem 6 (10 points)

Take 5 `R` functions of your choice and find/compare/contrast their parameters, output, and usability with the `python` function that accomplishes the same goal. (2 points per function comparison)

